services:
  feedproxy:
    build: ./
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
      DATABASE_PATH: /data/feedproxy.db
      SECRET_KEY_BASE: GtEq3jHhpTOVjr6gxIAV93gQszJG70ijQQoKbYPJqYBUZG0LTo9Dwlp9mmyKbRfiRz3N2oYycwBoppr3UuSNmQ==  # openssl rand -base64 64
    volumes:
      - ./data:/data
    ports:
    - "4000:4000"
